// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

package vmtest_test

import (
	"encoding/json"
	"fmt"
	"slices"
	"strings"
	"testing"
	"time"

	"tailscale.com/cmd/tailscale/tsdnsjsonv0"
	"tailscale.com/health"
	"tailscale.com/net/dns"
	"tailscale.com/tailcfg"
	"tailscale.com/tstest"
	"tailscale.com/tstest/natlab/vmtest"
	"tailscale.com/tstest/natlab/vnet"
	"tailscale.com/types/dnstype"
)

// The openresolv tests use a routed domain that is answered locally from an
// extra record. That is the cheapest DNS config that still reaches
// GetBaseConfig. It has no default resolvers, which would short-circuit
// compileConfig. It also takes no split-DNS shortcut, because openresolv
// reports SupportsSplitDNS() == false.
const (
	orMagicDNSDomain = "tailnet.test"
	orLocalDomain    = "local.example"
	orLocalName      = "host." + orLocalDomain

	// This address is outside the 100.64.x.y block testcontrol assigns to
	// nodes, so an answer can only have come from the extra record.
	orLocalIP = "100.99.99.99"

	// The signature line openresolv writes at the top of resolv.conf.
	orSignature = "# Generated by resolvconf"

	// A name that no route covers and that only vnet's default DNS server
	// answers. Resolving it proves the query reached the base config's
	// nameservers instead of being answered by quad-100.
	orUpstreamOnlyName = "dualstack-web.example.com"
	orUpstreamOnlyIP   = "5.0.0.100"

	// Tailscale's own resolver. tailscaled points resolv.conf at it once it has
	// configured DNS.
	orQuad100 = "100.100.100.100"
)

// newOpenresolvEnv brings up a single Ubuntu node running upstream openresolv
// with an existing but empty snippet directory, so openresolv has no snippets
// registered until something adds one.
func newOpenresolvEnv(t *testing.T) (*vmtest.Env, *vmtest.Node) {
	t.Helper()
	env := vmtest.New(t,
		vmtest.ControlDNS(orMagicDNSDomain, &tailcfg.DNSConfig{
			Proxied: true, // MagicDNS, so there's a route and quad-100 is in play
			Domains: []string{orLocalDomain},
			Routes: map[string][]*dnstype.Resolver{
				orLocalDomain: nil, // answer locally, from ExtraRecords
			},
			ExtraRecords: []tailcfg.DNSRecord{
				{Name: orLocalName, Type: "A", Value: orLocalIP},
			},
		}))
	node := env.AddNode("node",
		env.AddNetwork("2.1.1.1", "192.168.1.1/24", vnet.EasyNAT),
		vmtest.OS(vmtest.Ubuntu2404),
		vmtest.WithDNSMode(vmtest.DNSOpenresolv))
	env.Start()

	// Otherwise a pass could come from a different DNS manager.
	env.AssertDNSBackend(node, "openresolv")
	return env, node
}

// TestOpenresolvDNS checks what tailscaled does on a host where openresolv has
// no snippets registered, so Tailscale's would be the only one. Before the fix
// for tailscale/tailscale#20825, resolvconf's exit status 2 aborted DNS
// configuration with a health error. Now openresolv reports an empty base
// config, so tailscaled has no upstream to forward public names to. It leaves
// resolv.conf alone and reports that it is waiting for system DNS servers
// (tailscale/tailscale#20341).
func TestOpenresolvDNS(t *testing.T) {
	env, node := newOpenresolvEnv(t)

	// Wait for tailscaled to report that it is holding off. Checking
	// resolv.conf alone proves nothing, since the file also looks untouched
	// before tailscaled has tried.
	assertEmptyBaseConfigWarning(t, env, node)

	// resolv.conf keeps the nameserver natlab provisioned, and quad-100 is not
	// installed, since it would have nothing to forward public names to.
	assertOpenresolvResolvConf(t, env, node,
		[]string{orSignature, vnet.FakeDNSIPv4().String()},
		[]string{orQuad100})

	// An empty base config is not a read failure.
	assertNoDNSReadWarning(t, env, node)

	// Tailscale did not register its snippet, so openresolv still has none.
	// resolvconf exits 2 in that state, which is what aborted DNS configuration
	// before the fix for #20825.
	const cmd = "resolvconf -i; echo rc=$?"
	if out, err := env.SSHExec(node, cmd); err != nil {
		t.Errorf("%s: %v (%s)", cmd, err, strings.TrimSpace(out))
	} else if got := strings.Fields(out); !slices.Equal(got, []string{"rc=2"}) {
		t.Errorf("%s = %q, want no snippets and exit status 2", cmd, strings.TrimSpace(out))
	}

	// The provisioned resolv.conf still works for public names.
	assertResolves(t, env, node, orUpstreamOnlyName, orUpstreamOnlyIP)

	// openresolv has no snippets, so it has no OS config to report: both the
	// nameservers and the search domains must come back empty, with no error.
	base := openresolvBaseConfig(t, env, node)
	if base == nil {
		return // openresolvBaseConfig already reported it
	}
	if len(base.Nameservers) != 0 || len(base.SearchDomains) != 0 {
		t.Errorf("OS base config = %+v, want it empty: openresolv has no "+
			"snippets, so it has no OS config to report "+
			"(tailscale/tailscale#20825)", *base)
	}
}

// TestOpenresolvDNSOtherSnippet is the counterweight to TestOpenresolvDNS.
// When another snippet is present, its nameservers must still become quad-100's
// default upstream. Without this test, the fix for #20825 could return early on
// every host and still look correct.
func TestOpenresolvDNSOtherSnippet(t *testing.T) {
	env, node := newOpenresolvEnv(t)

	// Register a second snippet, the way a DHCP client would. It points at
	// vnet's default DNS server, the only thing that answers
	// orUpstreamOnlyName.
	cmd := fmt.Sprintf("printf 'nameserver %s\\n' | resolvconf -a eth0.inet", vnet.FakeDNSIPv4())
	if out, err := env.SSHExec(node, cmd); err != nil {
		t.Fatalf("%s: %v (%s)", cmd, err, strings.TrimSpace(out))
	}

	// tailscaled has no reason to re-read the OS config on its own, so force a
	// full reapply. This is also how the reporter of #20825 reproduced the bug.
	env.SetAcceptDNS(node, false)
	env.SetAcceptDNS(node, true)

	// Both snippets are registered.
	if out, err := env.SSHExec(node, "resolvconf -i"); err != nil {
		t.Errorf("resolvconf -i: %v (%s)", err, strings.TrimSpace(out))
	} else {
		// Match whole fields, so "tailscale" does not match a longer snippet
		// name.
		got := strings.Fields(out)
		for _, want := range []string{"eth0.inet", "tailscale"} {
			if !slices.Contains(got, want) {
				t.Errorf("resolvconf -i = %q, want it to list %q", strings.TrimSpace(out), want)
			}
		}
	}

	// Tailscale still owns resolv.conf, so the OS asks quad-100 rather than the
	// other snippet directly. Check that before the lookup at the end of the
	// test. Otherwise a successful lookup might only mean libc went straight to
	// the other snippet's nameserver during the toggle above.
	assertOpenresolvResolvConf(t, env, node,
		[]string{orSignature, orQuad100},
		[]string{vnet.FakeDNSIPv4().String()})

	assertNoDNSReadWarning(t, env, node)

	// tailscaled must read back the other snippet's nameserver and nothing else.
	// An empty config would mean the #20825 early return fired when it should
	// not have, and our own snippet would mean the quad-100 filter did not
	// (tailscale/tailscale#7816).
	if base := openresolvBaseConfig(t, env, node); base != nil {
		if want := vnet.FakeDNSIPv4().String(); !slices.Equal(base.Nameservers, []string{want}) {
			t.Errorf("OS base config nameservers = %q, want just %s", base.Nameservers, want)
		}
	}

	// An answer here can only come from quad-100 forwarding to that base config,
	// since nothing else on the guest answers this name.
	assertResolves(t, env, node, orUpstreamOnlyName, orUpstreamOnlyIP)
}

// orDeadNameserver is a nameserver nothing answers. It is in TEST-NET-2, which
// vnet routes nowhere: the router drops packets for it silently.
const orDeadNameserver = "198.51.100.53"

// TestOpenresolvDNSSnippetChange checks that tailscaled picks up a change to
// another snippet's nameservers when nothing else about the network changes.
// A DHCP lease renewal that carries new DNS servers looks like this: the
// client's resolvconf hook re-registers its snippet, and there is no netlink
// event. See tailscale/tailscale#21607.
func TestOpenresolvDNSSnippetChange(t *testing.T) {
	env, node := newOpenresolvEnv(t)

	// The DHCP snippet starts out pointing at a nameserver nothing answers.
	addOpenresolvSnippet(t, env, node, "eth0.dhcp", orDeadNameserver)

	// Make tailscaled read the snippet and take over resolv.conf.
	env.SetAcceptDNS(node, false)
	env.SetAcceptDNS(node, true)
	assertOpenresolvResolvConf(t, env, node,
		[]string{orSignature, orQuad100},
		[]string{orDeadNameserver})

	// The lease renews with a working nameserver.
	addOpenresolvSnippet(t, env, node, "eth0.dhcp", vnet.FakeDNSIPv4().String())

	// tailscaled can read the new nameserver back.
	if base := openresolvBaseConfig(t, env, node); base != nil {
		if want := vnet.FakeDNSIPv4().String(); !slices.Equal(base.Nameservers, []string{want}) {
			t.Fatalf("OS base config nameservers after renewal = %q, want just %s", base.Nameservers, want)
		}
	}

	// Public names must resolve through quad-100 within a reasonable time.
	assertResolves(t, env, node, orUpstreamOnlyName, orUpstreamOnlyIP)
}

// TestOpenresolvDNSDHCPHookRace checks that tailscaled picks up the DNS
// servers a DHCP lease carries when dhcpcd rebinds the lease. dhcpcd
// configures the interface first and runs its resolvconf hook afterwards, so
// the nameservers are registered some time after the netlink events. See
// tailscale/tailscale#21607.
//
// The guest runs systemd-networkd, not dhcpcd, so the test performs dhcpcd's
// steps itself over SSH, in dhcpcd's order.
func TestOpenresolvDNSDHCPHookRace(t *testing.T) {
	env, node := newOpenresolvEnv(t)

	// dhcpcd registers one snippet per interface and protocol. The RA
	// snippet carries a nameserver that nothing answers, and it outlives the
	// DHCP lease.
	addOpenresolvSnippet(t, env, node, "eth0.ra", orDeadNameserver)
	addOpenresolvSnippet(t, env, node, "eth0.dhcp", vnet.FakeDNSIPv4().String())

	// Make tailscaled read both snippets and take over resolv.conf.
	env.SetAcceptDNS(node, false)
	env.SetAcceptDNS(node, true)
	assertOpenresolvResolvConf(t, env, node,
		[]string{orSignature, orQuad100},
		[]string{vnet.FakeDNSIPv4().String()})

	// quad-100 forwards to both nameservers, so the dead one does not
	// prevent resolution.
	assertResolves(t, env, node, orUpstreamOnlyName, orUpstreamOnlyIP)

	// Count the resolver configs compiled so far. The replay must add one.
	before := len(resolverCfgLogs(t, env, node))
	if before == 0 {
		t.Fatal("no Resolvercfg lines in tailscaled's log")
	}

	// Replay dhcpcd rebinding a lease that expired. The hook removed
	// eth0.dhcp at expiry. On rebind, dhcpcd configures the address, then
	// runs the hook, which adds the snippet back. The sleep stands in for
	// the time the hook takes to run. The /32 is outside the LAN and changes
	// nothing about what the guest can reach; it exists only to produce the
	// netlink event that dhcpcd's own address change would.
	cmd := fmt.Sprintf(`set -e
dev=$(ip -4 -o route show default | sed -n 's/.* dev \([^ ]*\).*/\1/p' | head -n1)
resolvconf -d eth0.dhcp -f
ip addr add 10.123.45.67/32 dev "$dev"
sleep 0.5
printf 'nameserver %s\n' | resolvconf -a eth0.dhcp
`, vnet.FakeDNSIPv4())
	if out, err := env.SSHExec(node, cmd); err != nil {
		t.Fatalf("replaying dhcpcd: %v (%s)", err, strings.TrimSpace(out))
	}

	// The lease's nameserver is registered again, and tailscaled can read it.
	if base := openresolvBaseConfig(t, env, node); base != nil {
		if want := vnet.FakeDNSIPv4().String(); !slices.Contains(base.Nameservers, want) {
			t.Fatalf("OS base config nameservers after replay = %q, want %s among them", base.Nameservers, want)
		}
	}

	// Some resolver config compiled since the replay must include the
	// lease's nameserver.
	var since []string
	if err := tstest.WaitFor(60*time.Second, func() error {
		since = resolverCfgLogs(t, env, node)[before:]
		for _, line := range since {
			if strings.Contains(line, vnet.FakeDNSIPv4().String()) {
				return nil
			}
		}
		return fmt.Errorf("no resolver config since the replay includes %s", vnet.FakeDNSIPv4())
	}); err != nil {
		t.Errorf("%v (tailscale/tailscale#21607); configs compiled since the replay:\n%s",
			err, strings.Join(since, "\n"))
	}

	// Public names must still resolve.
	assertResolves(t, env, node, orUpstreamOnlyName, orUpstreamOnlyIP)
}

// addOpenresolvSnippet registers a resolvconf snippet with the given name and
// single nameserver on the node, the way a DHCP client's hook would.
func addOpenresolvSnippet(t *testing.T, env *vmtest.Env, n *vmtest.Node, name, nameserver string) {
	t.Helper()
	cmd := fmt.Sprintf("printf 'nameserver %s\\n' | resolvconf -a %s", nameserver, name)
	if out, err := env.SSHExec(n, cmd); err != nil {
		t.Fatalf("%s: %v (%s)", cmd, err, strings.TrimSpace(out))
	}
}

// resolverCfgLogs returns the "dns: Resolvercfg" lines tailscaled has logged
// so far, oldest first. Each is the resolver configuration tailscaled compiled
// on one DNS set.
//
// It reads cloud-init's output log, where tailscaled's output lands because
// cloud-init's runcmd started it. Cloud-image guests do not upload to the fake
// log catcher; only gokrazy guests trust its certificate.
func resolverCfgLogs(t *testing.T, env *vmtest.Env, n *vmtest.Node) []string {
	t.Helper()
	const cmd = "grep -F 'dns: Resolvercfg:' /var/log/cloud-init-output.log || true"
	out, err := env.SSHExec(n, cmd)
	if err != nil {
		t.Fatalf("%s: %v (%s)", cmd, err, strings.TrimSpace(out))
	}
	out = strings.TrimSpace(out)
	if out == "" {
		return nil
	}
	return strings.Split(out, "\n")
}

// assertOpenresolvResolvConf waits for the guest's /etc/resolv.conf to contain
// every string in want and none in notWant.
func assertOpenresolvResolvConf(t *testing.T, env *vmtest.Env, n *vmtest.Node, want, notWant []string) {
	t.Helper()
	const cmd = "cat /etc/resolv.conf"
	var last string
	if err := tstest.WaitFor(60*time.Second, func() error {
		out, err := env.SSHExec(n, cmd)
		last = out
		if err != nil {
			return fmt.Errorf("%s: %v (%s)", cmd, err, strings.TrimSpace(out))
		}
		for _, w := range want {
			if !strings.Contains(out, w) {
				return fmt.Errorf("resolv.conf is missing %q", w)
			}
		}
		for _, w := range notWant {
			if strings.Contains(out, w) {
				return fmt.Errorf("resolv.conf unexpectedly has %q", w)
			}
		}
		return nil
	}); err != nil {
		// The health lines are the fastest way to tell "DNS was never applied"
		// from "DNS was applied but looks wrong".
		t.Fatalf("%v\nwant all of %q and none of %q in resolv.conf:\n%s\nhealth: %q",
			err, want, notWant, last, env.Status(n).Health)
	}
}

// openresolvBaseConfig returns what tailscaled reads back as the node's own OS
// DNS configuration. On failure it calls t.Errorf and returns nil.
//
// "tailscale dns status" fetches it over the local API, which calls straight
// through to openresolvManager.GetBaseConfig, so this is the live result of
// running resolvconf in the guest, not something inferred from its consequences.
func openresolvBaseConfig(t *testing.T, env *vmtest.Env, n *vmtest.Node) *tsdnsjsonv0.SystemConfig {
	t.Helper()
	const cmd = "tailscale dns status --json"
	out, err := env.SSHExec(n, cmd)
	if err != nil {
		t.Errorf("%s: %v (%s)", cmd, err, strings.TrimSpace(out))
		return nil
	}
	var st tsdnsjsonv0.StatusResponse
	if err := json.Unmarshal([]byte(out), &st); err != nil {
		t.Errorf("parsing %s output: %v\n%s", cmd, err, out)
		return nil
	}
	if st.SystemDNSError != "" {
		t.Errorf("tailscaled could not read the OS DNS config: %q", st.SystemDNSError)
		return nil
	}
	if st.SystemDNS == nil {
		t.Errorf("%s reported no OS DNS config:\n%s", cmd, out)
		return nil
	}
	return st.SystemDNS
}

// assertEmptyBaseConfigWarning waits until the node's health list includes the
// warning that the OS has no DNS servers for Tailscale to forward to.
func assertEmptyBaseConfigWarning(t *testing.T, env *vmtest.Env, n *vmtest.Node) {
	t.Helper()
	// Taking the text from the Warnable rather than copying its wording keeps
	// this check from silently going stale if the wording changes.
	want := dns.EmptyBaseConfigWarnable.Text(nil)
	var last []string
	if err := tstest.WaitFor(60*time.Second, func() error {
		last = env.Status(n).Health
		if slices.Contains(last, want) {
			return nil
		}
		return fmt.Errorf("health does not include %q", want)
	}); err != nil {
		t.Fatalf("%v\nhealth: %q", err, last)
	}
}

// assertNoDNSReadWarning fails if the node is reporting that it could not read
// the OS DNS configuration.
func assertNoDNSReadWarning(t *testing.T, env *vmtest.Env, n *vmtest.Node) {
	t.Helper()
	// The warning ends with the error text, so match on what comes before it.
	// Taking that from the Warnable rather than copying its wording matters
	// here: this check asserts an absence, so a copy that stopped matching
	// would leave the check passing while testing nothing.
	want := dns.OSConfigurationReadWarnable.Text(health.Args{health.ArgError: ""})
	for _, h := range env.Status(n).Health {
		if strings.HasPrefix(h, want) {
			t.Errorf("node is unhealthy: %q", h)
		}
	}
}

// assertResolves waits for name to resolve to want on the node. It asks for A
// records only, so a name with both an A and a AAAA record cannot come back as
// the wrong address family.
func assertResolves(t *testing.T, env *vmtest.Env, n *vmtest.Node, name, want string) {
	t.Helper()
	cmd := "getent ahostsv4 " + name
	if err := tstest.WaitFor(30*time.Second, func() error {
		out, err := env.SSHExec(n, cmd)
		if err != nil {
			return fmt.Errorf("%s: %v (%s)", cmd, err, strings.TrimSpace(out))
		}
		if !strings.Contains(out, want) {
			return fmt.Errorf("%s = %q, want it to contain %s", cmd, strings.TrimSpace(out), want)
		}
		return nil
	}); err != nil {
		out, _ := env.SSHExec(n, "cat /etc/resolv.conf; resolvconf -i")
		t.Errorf("%v\nresolver state:\n%s", err, out)
	}
}
